# Generated by Django 5.2.8 on 2026-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
