# Generated by Django 5.2.8 on 2026-02-12 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_event_type', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_metadata', models.JSONField(default=dict, help_text='Metadata received from Stripe in this event')),
                ('payload_snapshot', models.JSONField(help_text='Full Stripe event payload as received')),
                ('processed_successfully', models.BooleanField(default=False)),
                ('stripe_created_at', models.DateTimeField(help_text='Timestamp when Stripe created the event')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='payment.order')),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
    ]
